handlers=java.util.logging.FileHandler,java.util.logging.ConsoleHandler
.level=INFO

# File Handler
java.util.logging.FileHandler.pattern=%t/mouse-debug.log
java.util.logging.FileHandler.limit=100000
java.util.logging.FileHandler.count=1
java.util.logging.FileHandler.formatter=java.util.logging.SimpleFormatter
java.util.logging.FileHandler.level=ALL
java.util.logging.FileHandler.append=true

# Console Handler
java.util.logging.ConsoleHandler.level=ALL
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter

# Formatter
java.util.logging.SimpleFormatter.format=%1$tF %1$tT [%4$s] %5$s%6$s%n

# Package levels
com.ftsoft.mdt.level=ALL
